### PR TITLE
add support for STRAPPEND, ARRAPPEND, ARRINSERT, ARRPOP, ARRINDEX, ARRTRIM, OBJKEYS

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by gkorland** [comment]
fix #13 #15

**Comment by gkorland** [comment]
#ref 18 add support for RDB READ/WRITE

**Review by gavrie — CHANGES_REQUESTED** [review]
Please see my commits on your `gkor` branch in which I refactored the code to more idiomatic Rust; assuming we agree, the other methods should be refactored as well.

**Comment by gkorland** [comment]
@gavrie It looks good thanks!

**Pull request merged**
